version: '3'
services:
  kafka:
    image: "spotify/kafka"
    ports:
      - "9092:9092"
      - "2181:2181"
    hostname: kafka
    expose:
      - "9092"
      - "2181"
  jobmanager:
    build: kaflinkshop
    expose: 
      - "6123"
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - KAFKA_HOST=kafka
  taskmanager:
    image: "flink:1.8.0"
    expose: 
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - KAFKA_HOST=kafka
  api:
    build: api
    ports:
      - "5000:5000"
      - "8080:8080"
    depends_on:
      - "kafka"
      - "jobmanager"
    environment:
      - KAFKA_HOST=kafka
networks:
  default:    
    driver: bridge